name: Deploy
on:
  push:
branches: [ main ]

jobs:
  EC2-Deploy:
runs-on: ubuntu-latest
environment:
  name: ${{ github.ref_name }}
  url: ${{ steps.deploy.outputs.vm_url }}
steps:
  - id: deploy
    name: Deploy
    uses: bitovi/github-actions-deploy-docker-to-ec2@v0.5.0
    with:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      aws_default_region: us-east-1
      app_port: 3000